# Generated by Django 5.0.5 on 2025-02-17 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='end_month',
            field=models.DateField(default=datetime.datetime(2026, 2, 17, 13, 26, 36, 984101, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
