# Generated by Django 5.0.5 on 2025-02-18 15:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_goal_end_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_month',
            field=models.DateField(default=datetime.datetime(2026, 2, 18, 15, 55, 30, 121891, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
