services:
    db:
        container_name: MySQL
        image: mysql:8.0
        volumes:
            - db-store:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            TZ: 'Asia/Tokyo'
        env_file:
            - .env
        ports:
            - "3306:3306"
        healthcheck:
            test: mysqladmin ping
            interval: 15s
            retries: 5

    web:
        container_name: Django
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy
        tty: true
        stdin_open: true

volumes:
    db-store: