# Generated by Django 5.0.5 on 2025-02-03 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_goal_end_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timer',
            old_name='duration',
            new_name='study',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='is_study',
        ),
        migrations.AddField(
            model_name='timer',
            name='rest',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='goal',
            name='end_month',
            field=models.DateField(default=datetime.datetime(2026, 2, 3, 15, 57, 42, 739452, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
