# Generated by Django 5.0.5 on 2025-01-25 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='end_month',
            field=models.DateField(default=datetime.datetime(2026, 1, 25, 9, 45, 27, 392077, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
