# Generated by Django 5.0.5 on 2025-01-21 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_study_log_user_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='end_month',
            field=models.DateField(default=datetime.datetime(2026, 1, 21, 15, 5, 48, 193180, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
